### ISSUE TITLE
Request: Would it be possible to add support for Steam Controller?

### ISSUE THREAD

**Issue by 8BitCerberus** [RetroWeeb/open-joystick-display#1]
I just found this and I'm very appreciative of the Linux support! I'll be using this for my PS4 and 8Bitdo controllers.

I've been looking for a Linux-friendly HUD for my Steam Controller, on Windows I use VSCView: https://github.com/Nielk1/VSCView and I wonder if it would be possible to use that as a springboard to get an idea of how to display the touchpad and gyro inputs?

**Comment by RetroWeeb** [comment]
I'm sorry I didn't see your ticket. You're the first person to do this correctly and not just ask me directly on discord! :)

I don't have a Steam Controller to test but I have a friend I can borrow from, I can look into it and put it on the roadmap. Gyros are supported in regards to the engine (chromium/electron) but I haven't implemented them into a theme level.

Can you send me screenshots of your current setup in VSCView and I can try and work from there.

**Comment by RetroWeeb** [comment]
I've added to the roadmap. Send me some info and I'll try and get my hands on a steam controller and we'll go from there.

**Comment by RetroWeeb** [comment]
@8BitCerberus I have been unable to get my hands on a steam controller. 

Cheapest used units are 35 or higher and to be completely honest I'm not about to go out and spend that money on a controller I won't use (I've used one, I don't like them, also I'm not really making my money on my application, in fact between server costs- it's costing me). 

I've added it to the roadmap, if I end up getting one cheap or finding someone who does own one I will add it to the OJD. In the meantime I'm going to have to shelf this.

As an alternative to waiting, If you're willing to let me borrow one I'll be happy to add the feature and then ship it back to you. You can ping me on discord and we can exchange info to do so, just join our channel and tag me, we can PM there.

Thanks.

**Comment by 8BitCerberus** [comment]
Hey, no problem. Definitely understandable not wanting to spend money on something you won't be using yourself. I'll see if I can get my hands on a spare one I can send to you. In the meantime, since you requested it earlier I'm attaching a screenshot so you can see what it looks like when running. It's a pretty simple setup, just a graphic of the controller on a green (or customizable color) background that can be keyed out in OBS.

![screenshot from 2019-02-23 17-57-10](https://user-images.githubusercontent.com/7584289/53293181-ae45ac80-3794-11e9-810a-7399d607f831.png)

And for what it looks like in use, [here's a video clip](https://www.youtube.com/watch?v=6agBdn-awt4).

**Comment by Readek** [comment]
I'm also interested in SC support! There's another project that kind of does this called [sc-controller](https://github.com/kozec/sc-controller). I don't know if its still useful, but you can look there how its UI looks like. Also, I imagine implementing SC support won't be as easy as the other ones, so you can ask for help there.

And thank you for supporting Linux!

**Comment by Formedras** [comment]
Unfortunately, ONLY Linux can support the Steam Controller, due to how its drivers work. Basically, when platforms without sc-controller see the controller without Steam running, the controller is acting in Lizard Mode, which mimics a keyboard and mouse. And when Steam is running, only Steam sees the raw controller data, and everything else (if that much) sees what Steam Input tells it to see. (Windows 8/8.1/10 Store Apps only see the Desktop Base Configuration.)

In order for OJD to see the Steam Controller, it would have to hijack the raw device and interpret it itself, preferably then passing it on to the rest of the system.
