### ISSUE TITLE
Switching players

### ISSUE THREAD

**Issue by Bluesurfer6** [RetroWeeb/open-joystick-display#10]
Is there a way to switch between different player's controllers? I want to use 2 controllers and display them both using 2 instances of Open Joystick-display.

**Comment by RetroWeeb** [comment]
That is a good point- you can't currently do it. Let me see if I can get a fix in this week to support multiple controllers.

**Comment by RetroWeeb** [comment]
@Bluesurfer6 So I got it working (screenshot attached). If you let me know what OS and what bit (64 or 32) you're on I can send you a beta build and see if it works for you.

![Screenshot_2019-07-14_22-40-28](https://user-images.githubusercontent.com/46404303/61193289-834aef00-a688-11e9-901b-5cd99f5115f3.png)

**Comment by Bluesurfer6** [comment]
> @Bluesurfer6 So I got it working (screenshot attached). If you let me know what OS and what bit (64 or 32) you're on I can send you a beta build and see if it works for you.
> 
I'm on Windows 10 64 bit

**Comment by RetroWeeb** [comment]
@Bluesurfer6 well apparently my builds are broken- however after a lot of throwing things, I got it to build- please test this latest build and get back to me. Thanks! https://drive.google.com/file/d/1pc5dSnsVW4IAxytQOaqvQCgqmEsc9KJI/view?usp=sharing

**Comment by RetroWeeb** [comment]
I actually just released it after doing some testing myself and with others, you can just download the latest version here: https://ojdproject.com/downloads/windows/stable/x64/open-joystick-display-2.3-x64-windows.zip

**Comment by RetroWeeb** [comment]
I'm going to close this out, if you have any other concerns just respond to this ticket. Thanks!
