### ISSUE TITLE
High CPU and D-Pad not working

### ISSUE THREAD

**Issue by comatrix44** [RetroWeeb/open-joystick-display#11]
Hi,
first of all I wish to thank you about the great program.
As the title says, I have a high CPU usage reaching 15%, even more then OBS itself that is used to stream (with all the implementations included and believe me, there are A LOT).
I searched and read some thread about that, but no solutions found unfortunately (yes I adjusted the Poll Rate, but that just has a low noticeable decrease).
My PC configuration:

Processor: Intel Core i7-7700HQ
Graphics adapter: NVIDIA GeForce GTX 1050 Ti (Laptop) - 4096 MB, Core: 1493 - 1620 MHz, Memory: 1752 MHz, GDDR5, 21.21.13.7350 (ForceWare 373.50)
Memory: 16384 MB , DDR4-2400
Mainboard: Intel Sunrise Point, Intel Kaby Lake-H
Storage: Samsung PM961 MZVLW256HEHP, 256 GB SSD - 1TB HDD

Second issue I'm not able to configure the D-Pad, no matter what I chose, but checking the the Windows that works correctly, also confirmed by the GameTools for Windows that display the controller button default configurations, everything is working correctly and fine.

If you wish I can make a video to show you, may be it is me that I'm doing something wrong.
Thanks in advance

**Comment by RetroWeeb** [comment]
Good Morning @comatrix44,

High CPU usage complaints has been a problem with OJD and part of the reason I'm in middle of a rewrite in an attempt to reduce the amount of CPU cycles this application uses.

Truth be told, I'm really only seeing about 10% total CPU usage while active on my 4790k (Poll 10ms)- but it can vary. Raising the poll rate from 20ms to 30-40ms does drop the CPU usage from anywhere from 20-30% and in some cases 50% (depending on how high you're willing to go).

If none of that is your fancy- as of right now there isn't a solution- there will be hopefully as I continue to refactor.

In regards to your d-pad, what controller are you using? I tested my Xbox Controller and 8BitDo just now and it's working just fine with the latest build. There is a known issue that Pro Controllers/Pokken controllers need an external driver to work (which isn't a problem in Linux, only Windows).  Let me know which one you're using and we can go from there.

Let me know. Thanks!

**Comment by comatrix44** [comment]
OK here it is a video link about what I am encountering, I hope it helps and please don't kill me, I'm trying to find a solution https://youtu.be/6I9rds2rZww

**Comment by RetroWeeb** [comment]
@comatrix44 nice video! I have a PS3 controller here I can take a look at it after work. Exactly which driver are you using for the PS3 so I can build you a working configuration? In general using the triggers in the way to go for this, but it may take some work.

**Comment by comatrix44** [comment]
Bluetooth Controller MallTEK 2.4GHz Bluetooth Gamepad 
PC Microsoft Drivers 10.0.17134.648

May be because it is a bluetooth controller? Perhaps this is the issue...

**Comment by RetroWeeb** [comment]
I don't know that type of controller or brand, Amazon yields some results but no exact matches. Bluetooth does work for PS4 and Xbox One controllers so I doubt it's that. This may just be a result of using the chromium driver. Let me think on this and get back to you, unfortunately without that exact controller it's hard for me to replicate.

**Comment by RetroWeeb** [comment]
https://html5gamepad.com/

@comatrix44  Can you use this tool in your browser and make a video of you holding dpad up, dpad down, dpad left, dpad right in this order. (Call it out if you want to) and send it to me. That will help me figure out a good working configuration for you.

**Comment by comatrix44** [comment]
Here there is the video, and thanks for your support:

https://youtu.be/ZuRUnYHabGY

You have to wait a little time that YouTube can elaborate the video in HD, otherwise in in a really low resolution (360p I believe)

**Comment by RetroWeeb** [comment]
I will work on this issue this evening and get back to you. Thank you for the video!

**Comment by RetroWeeb** [comment]
Here is a new beta build for you to try: https://drive.google.com/file/d/15fTC7k9gw3GWyn_AN48WqtoJwSdzN5-A/view?usp=sharing

Here are some instructions in video format! Let me know how this goes.
https://www.youtube.com/watch?v=8CgaSgfpzSE&feature=youtu.be

**Comment by RetroWeeb** [comment]
Here is a new beta build for you to try:  @comatrix44 https://drive.google.com/file/d/15fTC7k9gw3GWyn_AN48WqtoJwSdzN5-A/view?usp=sharing

Here are some instructions in video format! Let me know how this goes.
https://www.youtube.com/watch?v=8CgaSgfpzSE&feature=youtu.be

**Comment by RetroWeeb** [comment]
https://drive.google.com/file/d/1OWtDJeWZd28Pn6Rxfe3A-XIu1JZDAgpE/view?usp=sharing

Here is a much more stable build to use instead @comatrix44

**Comment by comatrix44** [comment]
OMG!!! It works!!!
I think you have fixed ALL kind of problems and issues with ANY existing controller with that new trigger section, simply because it is a configurable data for any kind of input, that means that now OJD is compatible with ALL kind of Controllers/Joystick/Input in ANY Operating Suystem receives, even the weirdest ones.
Congratulations, really.

**Comment by RetroWeeb** [comment]
I'm glad I could help! I'm going to close out this ticket but keep an eye out because I will come back to it and tag you once more to let you know when the stable build is out. In the meantime feel free to keep using the one I provided for you (truth be told the final build will just have a couple of extra themes so nothing criticial).

Thanks!

**Comment by RetroWeeb** [comment]
@comatrix44 latest build is live on the website. Feel free to download 2.4 stable.

**Comment by comatrix44** [comment]
Nice, thank you.
There is a way to create a backup compatible from the previous/beta versions? I mean to export the Joystick configurations, otherwise we are always obligated to recreate every single Joystick every time a new version is released.

**Comment by comatrix44** [comment]
Thanks a lot, but think about adding that "Save" feature, if you think you can, it is not necessary but easier for less experienced users ^_^

**Comment by RetroWeeb** [comment]
@comatrix44 that is going to come with the rewrite in a few months. I think it's valuable to be able to backup your configurations if you're going from PC to PC.

**Comment by RetroWeeb** [comment]
One other thing, if you have time, could you please leave a review of OJD on the OBS forums. It goes a long way with ranking and getting the word out: https://obsproject.com/forum/resources/open-joystick-display.750/

**Comment by comatrix44** [comment]
Even more, I'm going to make a video tutorial if you wish, with your approval of course, talking about all the engagement you are putting in this piece of jewel that is OJD and, of course, going into simple steps of the software for every user, starting from this thread ^_^ (nothing about programing but showing the software implementations).
Let me Know

**Comment by RetroWeeb** [comment]
Go for it! Thank you so much :D
