### ISSUE TITLE
Swap JoyCon colors

### ISSUE THREAD

**Issue by sorenbug** [RetroWeeb/open-joystick-display#12]
I use the green and pink joycons, however since mine are imported from Japan the pink is + and the green is -. Currently in the software it's in the US/EU ordering:
![image](https://user-images.githubusercontent.com/7751296/61967328-e6daf380-af89-11e9-8a5b-223e0c48d898.png)
I'd like to switch them, but I feel it's better to have a universal solution for switching joycon colors.

Also, having arbitrary joycon colors might be something to think about when handling this.

**Comment by RetroWeeb** [comment]
All themes are svgs, feel free to take them from source and edit them in Inkscape to your own custom theme. I will take this into account when I release some new themes shortly.

Thanks
