### ISSUE TITLE
Streamer style for Switch controllers

### ISSUE THREAD

**Issue by sorenbug** [RetroWeeb/open-joystick-display#13]
I plan to actually try and do this but I figure I'd open an issue for it beforehand.

**Comment by RetroWeeb** [comment]
I already have them in the works but sure a ticket is fine.

**Comment by RetroWeeb** [comment]
Also note that if you’re going to make code modifications there is a massive rewrite in react happening at the moment, you’re free to make pull requests but I may end up merging them into the new architecture

**Comment by RetroWeeb** [comment]
@sorenbug version 2.5 has been released. It has your alternate colored joycons and streamer theme for Nintendo Switch. Let me know if this is to your liking.

Thanks!

**Comment by sorenbug** [comment]
Awesome! I was too busy to work on something, thanks for letting me know it's been done though!
