### ISSUE TITLE
yarn start produces blank window

### ISSUE THREAD

**Issue by sorenbug** [RetroWeeb/open-joystick-display#14]
![image](https://user-images.githubusercontent.com/7751296/61972222-e5afc380-af95-11e9-8ca8-ab4d6c0cef9b.png)

I'm on EndeavourOS (based on Arch) x86_64, I did `yay -S electron yarn` and then tried to run `yarn start` but I get this.

I'm trying to be able to run on git repo instead of the packaged version.

<details>
  <summary>Console log:</summary>

  
![image](https://user-images.githubusercontent.com/7751296/61972829-67ecb780-af97-11e9-8014-0c09fcdd725d.png)
</details>

**Comment by RetroWeeb** [comment]
You need to rebuild electron because the serial port driver needs a binary compiled. You need make and gcc/clans installed to do this, but the command order is simply 

Do this once:
yarn install
gulp rebuild-electron

Then afterwards going forward:
Yarn start

Let me know if that helps.

**Comment by sorenbug** [comment]
It opens. Thank you!
