### ISSUE TITLE
NES controller with Retrobit to USB converter axis fail

### ISSUE THREAD

**Issue by goldug** [RetroWeeb/open-joystick-display#3]
Hello!
This app is almost exactly what I've been looking for, but there is one problem. I'm using an original NES controller plugged in to my Retrobit to USB converter (NES to USB) and the d-pad isn't correctly interpreted.
This method makes the d-pad function like a stick (x=left and right, y=up and down), but Open-Joystick-Display only recognizes when I push right and down, never left and up. I've tried adding them as triggers, but that doesn't work at all. The app completely fails to react when I press any directional button.
One thing that might be a culprit is that both axes say Infinity when I push them.
I think it's because of the way OJD tries to find the gamepad (the html5-gamepad thing). I'm not sure that works at all with my setup.

**Comment by RetroWeeb** [comment]
Hey @goldug so in the most recent version of OJD I have a fix for the infinity problem by toggling the infinity setting which will check for -inf and inf. Did this not work out for you? Also, a video of the problem would help alot so I can help you build a configuration that works or identifiy how to make a fix. Thanks!

![image](https://user-images.githubusercontent.com/46404303/57163156-5d6ab980-6dbe-11e9-9639-df54269801c4.png)

**Comment by RetroWeeb** [comment]
@goldug it's been nearly a week with no response so I'm going to close this ticket. Please feel free to respond back to this ticket if you still need help with your configuration. Thanks!
