### ISSUE TITLE
New overlay

### ISSUE THREAD

**Issue by Carlof13** [RetroWeeb/open-joystick-display#6]
Can you make a switch pro controller overlay for O J D please

**Comment by RetroWeeb** [comment]
@Carlof13 I'm working on my own version of it as well as a Pokken controller. I'm currently in middle of a redevelopment of OJD and it may not be out for a bit, but if I can get some extra cycles in between that and life I will add it to the current codebase.

**Comment by RetroWeeb** [comment]
@Carlof13 the latest build of OJD now has a pro controller theme.
