### ISSUE TITLE
Custom overlay: "Couldn't load theme style list"

### ISSUE THREAD

**Issue by JapanYoshi** [RetroWeeb/open-joystick-display#7]
I'm trying to code a custom compact overlay with my own branding, and I'm trying to test the code, but when I try to select and load the overlay, the console gives me this error:

```
Couldn't load theme style list  D:\Downloads-open-jo...e.controller.js:468
renderThemesMenu @ D:\Downloads\open-jo…e.controller.js:468
render           @ D:\Downloads\open-jo…e.controller.js:585
onSelect         @ D:\Downloads\open-jo…e.controller.js:172
dispatch         @ D:\Downloads\open-jo…dist\jquery.js:5183
elemData.handle  @ D:\Downloads\open-jo…dist\jquery.js:4991
ListPicker._handleMouseUp
```

I *think* I've followed all the steps in the [developer's guide](https://ojdproject.com/developer-guide#theme-styles), but in case this is a C2KI error, I've attached my draft so far.
[haleyhalcyon.zip](https://github.com/RetroWeeb/open-joystick-display/files/3339286/haleyhalcyon.zip)

**Comment by RetroWeeb** [comment]
@JapanYoshi can you give me a screenshot of what you're attempting to do (the design) along with your files so I can debug it. Thanks!

**Comment by RetroWeeb** [comment]
Never mind I didn't see your link, let me look at it.

**Comment by RetroWeeb** [comment]
`{
	"id": "haleyhalcyon",
	"name": "HaleyHalcyon's Xbox",
	"author": "HaleyHalcyon",
	"version": "1.0",
	"copyright": "",
	"license": "BSD 4-Clause Attribution",
	"website": "https://ojdproject.com"
}`
Just remove the styles attribute since you're not doing multiple styles. That will fix your issues. Styles need to have their own css named after them.

**Comment by JapanYoshi** [comment]
Alright, thanks, that seems to have fixed the issue!
