### ISSUE TITLE
Stick Not Working

### ISSUE THREAD

**Issue by TBRGo2Sl3ep** [RetroWeeb/open-joystick-display#8]
I've set up all of the buttons for my fight stick, but the actual stick will not register to where I can set axis values. The program detects my stick, but won't register the axis i set a value for. I hope that made sense....

**Comment by RetroWeeb** [comment]
Can you post a video or a screenshot of you moving your stick in OJD showing the tester? I want to see what the tester shows. If the stick doesn't register in the tester panel that would be interesting.

What fight stick are you using?

**Comment by RetroWeeb** [comment]
I'm closing this ticket due to inactivity. If you any any extra information let me know, I'm happy to help.
